# Generated by Django 3.2.9 on 2021-11-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='titre')),
                ('description', models.TextField(verbose_name='contenu')),
                ('date', models.DateField(verbose_name='date de creation')),
                ('published', models.BooleanField(verbose_name='publié')),
            ],
        ),
        migrations.DeleteModel(
            name='blog_post',
        ),
    ]
